server {
    listen 80;
    root /var/www/html/web;
    index index.php;

    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~* \.(env|lock|yml|twig|sh)$ { deny all; }
    location ~ ^/sites/.*/private/ { deny all; }
}